[book]
authors = ["Equim"]
language = "en"
multilingual = false
src = "src"
title = "ğŸ€„ï¸Mortal Documentation"
description = "Mortal - a free and open source AI for Japanese mahjong"

[preprocessor.admonish]

[output.html]
default-theme = "rust"
mathjax-support = true
site-url = "/"
cname = "mortal.ekyu.moe"
git-repository-url = "https://github.com/Equim-chan/Mortal"
additional-css = ["css/mdbook-admonish.css", "css/extra.css"]
